Final/eclass_final/models/topic.py
from flask import session
from eclass_final.db import get_db


def get_all_topics():
    """ function to get all of the topics in database """
    error = ''
    db = get_db()
    cur = db.cursor()
    sql = """
        SELECT id, title, body FROM topics ORDER BY id
    """
    cur.execute(sql)
    topics = cur.fetchall()
    cur.close()

    return topics, error


def get_topic_by_id(id):
    """ function to get topic by id """
    error = ''
    db = get_db()
    cur = db.cursor()
    sql = """
        SELECT id, title, body FROM topics WHERE id = %d
    """ % (int(id))
    cur.execute(sql)
    topic = cur.fetchone()
    cur.close()

    if not topic:
        error = 'Invalid topic with id: %d' % id

    return topic, error


def create_topic(data):
    """ function to create topic based on data dict """
    # trust that data is already complete
    error = ''
    db = get_db()
    cur = db.cursor()
    try:
        sql = """
            INSERT INTO topics (title, body) VALUES ('%s', '%s')
        """ % (data.get('title'), data.get('body'))
        cur.execute(sql)
        db.commit()
    except db.IntegrityError as e:
        error = e
    cur.close()
    return None, error


def update_topic(data):
    """ function to update topic based on data dict """
    # trust that data is already complete
    error = ''
    db = get_db()
    cur = db.cursor()
    try:
        sql = """
            UPDATE topics SET title = '%s', body = '%s' WHERE id = %d
        """ % (data.get('title'), data.get('body'), data.get('id'))
        cur.execute(sql)
        db.commit()
    except db.IntegrityError as e:
        error = e
    cur.close()
    return None, error


def delete_topic(id):
    """ function to delete topic based on id """
    error = ''
    db = get_db()
    cur = db.cursor()
    try:
        sql = """
            DELETE FROM topics WHERE id = %d
        """ % (int(id))
        cur.execute(sql)
        db.commit()
    except db.IntegrityError as e:
        error = 'The topic have submission of students, it cannot be deleted.'
    except db.DatabaseError as e:
        error = e

    cur.close()
    return None, error


def topic_submission(data):
    """ function to submiy topic for student based on data dict """
    # trust that data is already complete
    error = ''
    db = get_db()
    cur = db.cursor()
    try:
        sql = """
            INSERT INTO submissions (user_id, topic_id, body) VALUES (%d, %d, '%s')
        """ % (session.get('user_id'), data.get('topic_id'), data.get('body'))
        cur.execute(sql)
        db.commit()
    except db.IntegrityError as e:
        error = e
    cur.close()
    return None, error

Final/eclass_final/controllers/topic.py
from flask import (
    Blueprint, render_template, jsonify, request, redirect, url_for, flash, session
)
import eclass_final.services.topic as svc_topic


bp = Blueprint('topic', __name__, url_prefix='/topic')


@bp.route('/detail/<int:id>', methods=['GET'])
def view(id):
    if not session.get('username'):
        return redirect(url_for('home'))

    topics, error = svc_topic.get_all()
    topic, error = svc_topic.get_by_id(id)
    flash(error)
    return render_template('topic/detail.html', topic=topic, topics=topics)


@bp.route('/create', methods=['GET', 'POST'])
def create():
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    err = ''
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        data = {
            'title': title.strip(),
            'body': body.strip()
        }
        _, error = svc_topic.save(data)
        if not error:
            return redirect(url_for('home'))

        flash(err)

    return render_template('topic/create.html')


@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    err = ''
    topic, error = svc_topic.get_by_id(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        data = {
            'id': int(id),
            'title': title.strip(),
            'body': body.strip()
        }
        _, error = svc_topic.save(data)
        if not error:
            return redirect(url_for('home'))

        flash(err)

    return render_template('topic/edit.html', topic=topic)


@bp.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    topic, error = svc_topic.get_by_id(id)
    if request.method == 'POST':
        _, error = svc_topic.delete(id)
        if not error:
            return redirect(url_for('home'))

    flash(error)
    return render_template('topic/delete.html', topic=topic)


@bp.route('/submit/<int:id>', methods=['GET', 'POST'])
def submit(id):
    if not session.get('username'):
        return redirect(url_for('home'))
        
    err = ''
    topic, error = svc_topic.get_by_id(id)

    if request.method == 'POST':
        user_id = session.get('user_id')
        body = request.form['body']
        data = {
            'user_id': int(user_id),
            'topic_id': int(id),
            'body': body.strip()
        }
        _, error = svc_topic.submit(data)
        if not error:
            return redirect(url_for('home'))

        flash(err)

    return render_template('submit/student_submission.html', topic=topic)

Final/eclass_final/templates/topic/create.html
{% extends "base.html" %}

{% block title %}
Add Topic
{% endblock %}

{% block content %}
<form method="POST">
    <div class="row mt-3 mb-3">
        <label for="title" class="col-2 col-form-label">Title</label>
        <div class="col-6">
            <input type="text" name="title" id="title" class="form-control" placeholder="Topic Title" required />
        </div>
    </div>
    <div class="row mb-3">
        <div class="offset-2 col-6">
            <textarea rows="8" cols="50" name="body" id="body"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="offset-2 col-6">
            <button class="btn btn-success" type="submit" name="btnCreate" id="btnCreate">Add</button>
        </div>
    </div>
</form>

<div>
    <a href="{{ url_for('home') }}">Back</a>
</div>
{% endblock %}

Final/eclass_final/templates/topic/delete.html
{% extends "base.html" %}

{% block title %}
Delete Topic
{% endblock %}

{% block content %}
<h1>Delete Page</h1>
{% if topic %}
<form action="/topic/delete/{{ topic[0] }}" method="POST">
    <div class="row mt-3 mb-3">
        Delete "{{ topic[1] }}" ?
    </div>
    <div class="row">
        <div class="offset-2 col-6">
            <button class="btn btn-danger" type="submit">Delete</button>
        </div>
    </div>
</form>
{% endif %}

{% if get_flashed_messages() %}
<div class="row mt-3">
    {% for msg in get_flashed_messages() %}
    <span>{{ msg }}</span>
    {% endfor %}
</div>
{% endif %}

<div>
    <a href="{{ url_for('home') }}">Back</a>
</div>
{% endblock %}

Final/eclass_final/templates/topic/detail.html
{% extends "base.html" %}

{% block title %}
{% if topic %}
{{ topic[0] }}
{% else %}
E-Class
{% endif %}

{% endblock %}

{% block content %}
<div class="row">
    {% if topic %}
    <h2>{{ topic[1] }}</h2>
    <p>
        {{ topic[2] }}
    </p>
    {% else %}
    <h3>
        Invalid Article
    </h3>
    {% endif %}
</div>

{% if topic and session.get('user_id') != 0 %}
<div class="row mb-3">
    <div class="card-body">
        <a href="{{ url_for('topic.submit', id=topic[0]) }}" class="btn btn-success">Add Submission</a>
    </div>
</div>
{% endif %}

<div>
    <a href="{{ url_for('home') }}">Back</a>
</div>
{% endblock %}

Final/eclass_final/templates/topic/edit.html
{% extends "base.html" %}

{% block title %}
Edit Topic
{% endblock %}

{% block content %}
<form action="/topic/edit/{{ topic[0] }}" method="POST">
    <div class="row mb-3">
        <label for="title" class="col-2 col-form-label">Title</label>
        <div class="col-6">
            <input type="text" name="title" id="title" class="form-control" placeholder="Topic Title"
                value="{{ topic[1] }}" required />
        </div>
    </div>
    <div class="row mb-3">
        <div class="offset-2 col-6">
            <textarea rows="8" cols="50" name="body" id="body">
                {{ topic[2] | trim }}
            </textarea>
        </div>
    </div>
    <div class="row">
        <div class="offset-2 col-6">
            <button class="btn btn-success" type="submit" name="btnEdit" id="btnEdit">Save</button>
        </div>
    </div>
</form>

<div>
    <a href="{{ url_for('home') }}">Back</a>
</div>
{% endblock %}