Final/eclass_final/controllers/topic.py
from flask import (
    Blueprint, render_template, jsonify, request, redirect, url_for, flash, session
)
import eclass_final.services.topic as svc_topic


bp = Blueprint('topic', __name__, url_prefix='/topic')


@bp.route('/detail/<int:id>', methods=['GET'])
def view(id):
    if not session.get('username'):
        return redirect(url_for('home'))

    topics, error = svc_topic.get_all()
    topic, error = svc_topic.get_by_id(id)
    flash(error)
    return render_template('topic/detail.html', topic=topic, topics=topics)


@bp.route('/create', methods=['GET', 'POST'])
def create():
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    err = ''
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        data = {
            'title': title.strip(),
            'body': body.strip()
        }
        _, error = svc_topic.save(data)
        if not error:
            return redirect(url_for('home'))

        flash(err)

    return render_template('topic/create.html')


@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    err = ''
    topic, error = svc_topic.get_by_id(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        data = {
            'id': int(id),
            'title': title.strip(),
            'body': body.strip()
        }
        _, error = svc_topic.save(data)
        if not error:
            return redirect(url_for('home'))

        flash(err)

    return render_template('topic/edit.html', topic=topic)


@bp.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    topic, error = svc_topic.get_by_id(id)
    if request.method == 'POST':
        _, error = svc_topic.delete(id)
        if not error:
            return redirect(url_for('home'))

    flash(error)
    return render_template('topic/delete.html', topic=topic)


@bp.route('/submit/<int:id>', methods=['GET', 'POST'])
def submit(id):
    if not session.get('username'):
        return redirect(url_for('home'))
        
    err = ''
    topic, error = svc_topic.get_by_id(id)

    if request.method == 'POST':
        user_id = session.get('user_id')
        body = request.form['body']
        data = {
            'user_id': int(user_id),
            'topic_id': int(id),
            'body': body.strip()
        }
        _, error = svc_topic.submit(data)
        if not error:
            return redirect(url_for('home'))

        flash(err)

    return render_template('submit/student_submission.html', topic=topic)

Final/eclass_final/controllers/user.py
from flask import (
    Blueprint, render_template, jsonify, request, redirect, url_for, flash, session
)
import eclass_final.services.user as svc_user

bp = Blueprint('user', __name__, url_prefix='/')


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    error = ''
    if request.method == 'POST':
        name = request.form['name']
        username = request.form['username']
        password = request.form['password']
        data = {
            'name': name.strip(),
            'username': username.strip(),
            'password': password.strip(),
        }
        _, error = svc_user.signup(data)
        if not error:
            return redirect(url_for('home'))

        flash(error)

    return render_template('user/signup.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    error = ''
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        data = {
            'username': username.strip(),
            'password': password.strip(),
        }
        _, error = svc_user.login(data)
        if not error and username == 'admin':
            return redirect(url_for('user.admin'))
        if not error and not username == 'admin':
            return redirect(url_for('home'))

        flash(error)

    return render_template('user/login.html')


@bp.route('/logout', methods=['GET', 'POST'])
def logout():
    """ function to do logout """
    session.clear()  # clear all sessions
    return redirect(url_for('home'))


@bp.route('/people_list', methods=['GET', 'POST'])
def get_all_users():
    if session.get('user_id') != 0:
        return redirect(url_for('home'))

    users, error = svc_user.get_all_users()
    flash(error)
    return render_template('user/list.html', users=users)


@bp.route('/classworks', methods=['GET', 'POST'])
def get_all_works():
    if session.get('user_id') != 0:
        return redirect(url_for('home'))
        
    works, error = svc_user.get_all_works()
    flash(error)
    return render_template('submit/student_work.html', works=works)

Final/eclass_final/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- <nav class="navbar navbar-expand container mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('home') }}">E-Class</a>
            <form class="d-flex">
                {% if session and session.get('username') %}
                <span>
                    {{ session['username'] }}
                </span>
                <a href="{{ url_for('user.logout') }}">Log Out</a>
                {% else %}
                <a href="{{ url_for('user.login') }}" class="btn btn-outline-primary me-2">Log In</a>
                <a href="{{ url_for('user.signup') }}" class="btn btn-primary">Sign Up</a>
                {% endif %}
            </form>
        </div>
    </nav> -->
    <div class="container">
        <nav
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="/"
                class="navbar-brand d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                E-Class
            </a>

            {% if session.get('user_id') == 0 %}
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ url_for('user.get_all_works') }}" class="nav-link px-2 link-dark">Classwork</a></li>
                <li><a href="{{ url_for('user.get_all_users') }}" class="nav-link px-2 link-dark">People</a></li>
            </ul>
            {% endif %}

            <div class="col-md-3 text-end">
                {% if session and session.get('username') %}
                <span>
                    Hello, {{ session['username'] }}
                </span>
                <a href="{{ url_for('user.logout') }}">Log Out</a>
                {% else %}
                <a href="{{ url_for('user.login') }}" class="btn btn-outline-primary me-2">Login</a>
                <a href="{{ url_for('user.signup') }}" class="btn btn-primary">Sign-up</a>
                {% endif %}
            </div>
        </nav>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

Final/eclass_final/templates/index.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
{% if session.get('username') %}
<div class="container d-grid gap-5">
    {% for id, title, body in topics %}
    <div class="card">
        <div class="card-header">
            {{ title }}
        </div>
        <div class="card-body">
            <p class="card-text">{{ body }}</p>
            {% if session.get('user_id') == 0 %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
                <a href="{{ url_for('topic.view', id=id) }}" type="button" class="btn btn-outline-primary">View</a>
                <a href="{{ url_for('topic.edit', id=id) }}" type="button" class="btn btn-outline-warning">Edit</a>
                <a href="{{ url_for('topic.delete', id=id) }}" type="button" class="btn btn-outline-danger">Delete</a>
            </div>
            {% else %}
            <a href="{{ url_for('topic.view', id=id) }}" type="button" class="btn btn-outline-primary">View</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% if session.get('user_id') == 0 %}
    <div class="card text-center">
        <div class="card-body">
            <a href="{{ url_for('topic.create') }}" class="btn btn-success">Add</a>
        </div>
    </div>
    {% endif %}
</div>
{% else %}
<center>
    <h3>Welcome to E-Class</h3>
    <h3>Please Login</h3>
</center>
{% endif %}
{% endblock %}